name: database-cosmos

dependencies:
  - python=3.8.2
  - pip=20.0.2

  - pip:
    - azure-cosmos==3.1.2
    - markdown>=3.1.1
    - pylint>=2.4.4
    - pep8>=1.7.1
    - autopep8>=1.5
    - pycodestyle>=2.5.0